name: Deploy to Alwaysdata

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch code from GitHub
        uses: actions/checkout@v4

      - name: Force Java 21 Installation
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: Build production JAR with Maven
        run: mvn clean package -DskipTests -Dmaven.test.skip=true

      - name: Upload files via SFTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.SFTP_SERVER }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: 22
          protocol: sftp
          local-dir: ./target/
          server-dir: ./
