spring.application.name=ProductsBackend
spring.datasource.url=jdbc:postgresql://localhost:5432/productsdb
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

jwt.secret=/JRLg7BE6sJICz0XFViG7z95mvGlvsSzNl84BwKrQOMV7oG3UthCbqmM8KsspU5SEaEsPmN6MbfkFRyOPqtKvQ==
jwt.expiration=86400000
